FROM centos

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl

RUN yum install wget -y

RUN chmod +x kubectl
RUN mv kubectl /usr/bin/
COPY ca.crt /root/
COPY client.crt /root/
COPY client.key /root/
COPY  myinfo    /
ADD myinfo /root/.kube/config

RUN wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
RUN rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
RUN yum install jenkins java-1.8.0-openjdk-devel -y
RUN yum install java-11-openjdk.x86_64 -y
RUN yum install git -y

CMD /etc/alternatives/java -Dcom.sun.akuma.Daemon=daemonized -Djava.awt.headless=true -DJENKINS_HOME=/var/lib/jenkins -jar /usr/lib/jenkins/jenkins.war --logfile=/var/log/jenkins/jenkins.log --webroot=/var/cache/jenkins/war --daemon --httpPort=8080 --debug=5 --handlerCountMax=100 --handlerCountMaxIdle=20


